src/Entity/RutaReservacion.php
<?php

namespace App\Entity;

use App\Repository\RutaReservacionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Gedmo\Timestampable\Traits\TimestampableEntity;

#[ORM\Entity(repositoryClass: RutaReservacionRepository::class)]
class RutaReservacion
{
    use TimestampableEntity;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\NotBlank]
    private ?Estacion $estacion_salida = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\NotBlank]
    private ?Estacion $estacion_llegada = null;

    #[ORM\OneToMany(mappedBy: 'ruta', targetEntity: Reservacion::class)]
    private Collection $reservaciones;

    public function __construct()
    {
        $this->reservaciones = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEstacionSalida(): ?Estacion
    {
        return $this->estacion_salida;
    }

    public function setEstacionSalida(?Estacion $estacion_salida): self
    {
        $this->estacion_salida = $estacion_salida;

        return $this;
    }

    public function getEstacionLlegada(): ?Estacion
    {
        return $this->estacion_llegada;
    }

    public function setEstacionLlegada(?Estacion $estacion_llegada): self
    {
        $this->estacion_llegada = $estacion_llegada;

        return $this;
    }

    /**
     * @return Collection<int, Reservacion>
     */
    public function getReservaciones(): Collection
    {
        return $this->reservaciones;
    }

    public function addReservacione(Reservacion $reservacione): self
    {
        if (!$this->reservaciones->contains($reservacione)) {
            $this->reservaciones->add($reservacione);
            $reservacione->setRuta($this);
        }

        return $this;
    }

    public function removeReservacione(Reservacion $reservacione): self
    {
        if ($this->reservaciones->removeElement($reservacione)) {
            // set the owning side to null (unless already changed)
            if ($reservacione->getRuta() === $this) {
                $reservacione->setRuta(null);
            }
        }

        return $this;
    }
}

src/Entity/SalidaReservacion.php
<?php

namespace App\Entity;

use App\Repository\SalidaReservacionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SalidaReservacionRepository::class)]
class SalidaReservacion
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $bus_clase = null;

    #[ORM\Column(nullable: true)]
    private ?int $minutos = null;

    #[ORM\Column(type: Types::BIGINT, nullable: true)]
    private ?string $salida_id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $salida_fecha = null;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $hora = null;

    #[ORM\OneToMany(mappedBy: 'salidaReservacion', targetEntity: Asiento::class, orphanRemoval: true)]
    private Collection $asientos;

    public function __construct()
    {
        $this->asientos = new ArrayCollection();
        $this->salida_fecha = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getBusClase(): ?string
    {
        return $this->bus_clase;
    }

    public function setBusClase(?string $bus_clase): self
    {
        $this->bus_clase = $bus_clase;

        return $this;
    }

    public function getMinutos(): ?int
    {
        return $this->minutos;
    }

    public function setMinutos(?int $minutos): self
    {
        $this->minutos = $minutos;

        return $this;
    }

    public function getSalidaId(): ?string
    {
        return $this->salida_id;
    }

    public function setSalidaId(?string $salida_id): self
    {
        $this->salida_id = $salida_id;

        return $this;
    }

    public function getSalidaFecha(): ?\DateTimeInterface
    {
        return $this->salida_fecha;
    }

    public function setSalidaFecha(\DateTimeInterface $salida_fecha): self
    {
        $this->salida_fecha = $salida_fecha;

        return $this;
    }

    public function getHora(): ?string
    {
        return $this->hora;
    }

    public function setHora($hora): self
    {
        $this->hora = $hora;

        return $this;
    }

    /**
     * @return Collection<int, Asiento>
     */
    public function getAsientos(): Collection
    {
        return $this->asientos;
    }

    public function addAsiento(Asiento $asiento): self
    {
        if (!$this->asientos->contains($asiento)) {
            $this->asientos->add($asiento);
            $asiento->setSalidaReservacion($this);
        }

        return $this;
    }

    public function removeAsiento(Asiento $asiento): self
    {
        if ($this->asientos->removeElement($asiento)) {
            // set the owning side to null (unless already changed)
            if ($asiento->getSalidaReservacion() === $this) {
                $asiento->setSalidaReservacion(null);
            }
        }

        return $this;
    }
}

templates/_contacto_form.html.twig
<turbo-frame id="contacto-form">

	{{form(form)}}

		{% if guardado %}
			{{ component('alert', {text: 'Hemos recibido su mensaje. Gracias por contactarnos.' | trans}) }}
		{% endif %}

	</turbo>

templates/_svg_loading.html.twig
<svg class="w-24" version="1.1" id="L4" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewbox="0 0 100 100" enable-background="new 0 0 0 0" xml:space="preserve">
	<circle fill="#3D92B2" stroke="none" cx="6" cy="50" r="6">
		<animate attributename="opacity" dur="1s" values="0;1;0" repeatcount="indefinite" begin="0.1"></animate>
	</circle>
	<circle fill="#3D92B2" stroke="none" cx="26" cy="50" r="6">
		<animate attributename="opacity" dur="1s" values="0;1;0" repeatcount="indefinite" begin="0.2"></animate>
	</circle>
	<circle fill="#3D92B2" stroke="none" cx="46" cy="50" r="6">
		<animate attributename="opacity" dur="1s" values="0;1;0" repeatcount="indefinite" begin="0.3"></animate>
	</circle>
	<circle fill="#3D92B2" stroke="none" cx="66" cy="50" r="6">
		<animate attributename="opacity" dur="1s" values="0;1;0" repeatcount="indefinite" begin="0.3"></animate>
	</circle>
	<circle fill="#3D92B2" stroke="none" cx="86" cy="50" r="6">
		<animate attributename="opacity" dur="1s" values="0;1;0" repeatcount="indefinite" begin="0.3"></animate>
	</circle>
</svg>

templates/_videos.html.twig
<turbo-frame id="videos" data-noloading="true">
	<section data-turbo-permanent class="pb-20 relative block bg-slate-400">
		<div class="bottom-auto top-0 left-0 right-0 w-full absolute pointer-events-none overflow-hidden -mt-20" style="height: 80px;">
			<svg class="absolute bottom-0 overflow-hidden" xmlns="http://www.w3.org/2000/svg" preserveaspectratio="none" version="1.1" viewbox="0 0 2560 100" x="0" y="0">
				<polygon class="text-slate-400 fill-current" points="2560 0 2560 100 0 100"></polygon>
			</svg>
		</div>
		<div class="container mx-auto px-4 lg:pt-16">
			<div class="contaidner mx-auto px-4">
				<div class="flex flex-wrap">
					<div class="lg:pt-12 pt-6 w-full md:w-4/12 px-4 text-center">
						<div class="mb-5 font-semibold text-xl text-center text-gray-700">
							{{'Clase Platino' | trans}}
						</div>
						<div class="relative flex flex-col min-w-0 break-words bg-white w-full mb-8 shadow-lg rounded-lg">

							<div class="aspect-w-16 aspect-h-9">
								<iframe class="shadow-2xl rounded-lg w-full" src="https://www.youtube.com/embed/J4G7FWdfKEc" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
							</div>
						</div>
					</div>
					<div class="w-full md:w-4/12 px-4 text-center">
						<div class="mb-5 font-semibold text-xl text-center text-gray-700">
							{{'Clase Oro' | trans}}
						</div>
						<div class="relative flex flex-col min-w-0 break-words bg-white w-full mb-8 shadow-lg rounded-lg">
							<div class="aspect-w-16 aspect-h-9">
								<iframe class="shadow-2xl rounded-lg w-full" src="https://www.youtube.com/embed/i96AR2v29U0" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
							</div>
						</div>
					</div>
					<div class="pt-6 w-full md:w-4/12 px-4 text-center ">
						<div class="mb-5 font-semibold text-xl text-center text-gray-700">
							{{'Excursiones' | trans}}
						</div>
						<div class="relative flex flex-col min-w-0 break-words bg-white w-full mb-8 shadow-lg rounded-lg">
							<div class="aspect-w-16 aspect-h-9">
								<iframe class="shadow-2xl rounded-lg w-full" src="https://www.youtube.com/embed/FHgIZX4UmAw" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="flex flex-wrap text-center justify-center">
				<div class="w-full lg:w-6/12 px-4">
					<p class="text-lg leading-relaxed mt-4 mb-4 font-medium">
						{{'Estamos en la mejor disposición de brindarle un servicio con calidad y elegancia a un cómodo precio. Nuestra experiencia en transporte de pasajeros es por mas de 50 años. La calidad de nuestro servicio es el resultado de su preferencia.' | trans}}
					</p>
				</div>
			</div>
		</div>
	</section>
</turbo-frame>

templates/base.html.twig
<!DOCTYPE html>
<html>
	<head>

		{% block seo %}
			{{ sonata_seo_metadatas() }}
		{% endblock %}

		<meta name="viewport" content="width=device-width, initial-scale=1"/>
		<link rel="shortcut icon" href="./assets/img/favicon.ico"/>
		<link rel="apple-touch-icon" sizes="76x76" href="./assets/img/apple-icon.png"/>

		{% block stylesheets %}
			{{ encore_entry_link_tags('app') }}
		{% endblock %}

		{% block javascripts %}
			{{ encore_entry_script_tags('app') }}
		{% endblock %}

		{% block title %}
			{{ sonata_seo_title() }}
		{% endblock %}

		<script>
			function toggleNavbar(collapseID) {
document.getElementById(collapseID).classList.toggle("hidden");
document.getElementById(collapseID).classList.toggle("block");
}
		</script>

	</head>
	<body class="antialiased">

		{{component('header')}}
		<main>
			{% block body %}{% endblock %}
		</main>
		{{component('footer')}}


		<div id="authentication_check_enrollment" {{ turbo_stream_listen('authentication_check_enrollment_' ~ app.session.id) }}></div>
		<noscript data-turbo="false">
			<iframe style="width: 100px; height: 100px; border: 0; position:absolute; top: -5000px;" src="https://h.online-metrix.net/fp/tags?org_id=k8vif92e&session_id={{cybersource_session_id}}"></iframe>
		</noscript>
	</body>
</html>

templates/contacto.html.twig
{% extends 'base.html.twig' %}

{% block body %}

	<section class="p-5 sm:px-20 mb-10">
		<div class="container mx-auto max-w-md">

			<div>
				{{component('alert', {text: 'Deje su mensaje y no pondremos en contacto con usted lo antes posible.' | trans})}}
			</div>

			{{ render_esi(controller('App\\Controller\\AppController::contactoForm')) }}

		</div>
	</section>
{% endblock %}

templates/estacion.html.twig
{% extends 'base.html.twig' %}

{% block body %}

	<section class="p-5 sm:px-20">
		<div class="container mx-auto">

			<div class="pt-10">
				{% for key, departamento in departamentos %}
					<details open>
						<summary>
							<span class="text-lg text-slate-700 font-semibold">{{departamento.nombre}}</span>
						</summary>
						<ul class="pl-10 list-disc">
							{% for key, estacion in departamento.estaciones %}
								<li class="prose prose-base max-w-none">
									<span class="text-slate-600 font-semibold">{{estacion.nombre}}</span>:
									<span class="italic">{{estacion.direccion}}</span>
								</li>
							{% endfor %}
						</ul>
					</details>


				{% endfor %}
			</div>
		</div>
	</section>
{% endblock %}

templates/historia.html.twig
{% extends 'base.html.twig' %}

{% block body %}

	<section class="p-5 sm:p-20">
		<div class="container mx-auto">
			<div class="prose lg:prose-xl prose-img:my-5 sm:prose-img:my-0 m-auto">
				<p>
					{{'La empresa Transportes Fuente Del Norte fue fundada en 1,958 por un hombre pionero y visionario, que a pesar de las condiciones viales no dejo que sus esfuerzos fueran en vano.' | trans}}</p>

				<p>{{'Su inicio se origino con un Pick-Up  que transportaba pasajeros de la aldea mariscos al crucé de trincheras, y una camionetilla de tres filas que salía de mariscos a los amates, así como de mariscos a puerto barrios.' | trans}}</p>
				<img class="max-w-full float-none sm:float-right shadow-2xl rounded-lg" src="{{asset('images/historia-1.jpg')}}"/>
				<p>{{'En el año de 1964 la Empresa Transportes Fuente del Norte da inicio a sus resultados  ya que adquiere la línea de transportes de bananera a Guatemala, siendo una posición que requería mucho esfuerzo y dedicación.' | trans}}</p>

				<p>{{'No muy lejano en el año 1969 da otro resultado la Empresa Transportes Fuente Del Norte ya que logra abrir brecha hacia el territorio Petenero, así como el área del atlántico,  lográndose la línea de transporte de Guatemala a puerto barrios y Guatemala a Santa Elena, Guatemala a la cruces, Guatemala a Melchor, esto era el resultado de un trabajo arduo y tenaz que se había establecido don Alfredo Mendoza Pellecer, con su empresa. Don Alfredo Mendoza al ver que la Empresa Transportes Fuente Del Norte, estaba dando pasos agigantados en el año 1981 tuvo que dialogar con la empresa litegua para definir áreas de trabajo llegando al mutuo acuerdo de que Transportes Fuente Del Norte tendría la línea de transporte de guatemala a peten, y transportes litegua de guatemala a puerto barrios.' | trans}}</p>

				<img class="max-w-full m-auto md:max-w-3xl shadow-2xl rounded-lg" src="{{asset('images/historia.jpg')}}"/>
				<p>{{'Don Alfredo Mendoza en su enfoque siempre pensó en la familia ya que se preocupo por dejar un legado a todos sus hijos y forjándolos para que su punto de vista siguiera mucho más lejos y así fueran los pioneros de las nuevas generaciones.' | trans}}</p>


				<p><img class="max-w-full float-none sm:float-right max-h-[500px] shadow-2xl rounded-lg" src="{{asset('images/historia-3.jpg')}}"/>
					{{'Esta nueva visión dio origen a un servicio de lujo dando origen al servicio de Autobuses Clase Oro y Maya de Oro. A la fecha la empresa Transportes Fuente Del Norte se ha extendido tanto dentro del país así como fuera del mismo, como lo es honduras, el salvador, belice, fronteras de méxico y belice.' | trans}}</p>
				<p>{{'Cuenta con el servicio de lujo con autobuses Clase Oro  de doble piso, para el sur y norte del país.  Cuenta con servicio de santa elena a cobán. Con sus respectivos derechos y autorizaciones de la dirección general de transportes.  Estos son los resultados de una persona pionera y soñadora  que con la Empresa Fuente Del Norte a llegado tan lejos dando un servicio a toda la población nacional con un 75% y extranjera.' | trans}}</p>
				<img class="max-w-full  m-auto md:max-w-3xl shadow-2xl rounded-lg" src="{{asset('images/historia-4.jpg')}}"/>

				<p>{{'Actualmente está constituida como sociedad anónima bajo el nombre de “Transportes Fuente Del Norte La Pionera, S.A.”' | trans}}</p>
				<ul>
					<li>
						<p class="font-medium">{{'Base legal' | trans}}</p>
						<p>{{'Empresa para servicio de transporte de pasajeros y carga  inscrita con patente de comercio de Sociedad  bajo el número de Registro 42723, folio 373, libro 136, de sociedades . Registrada el  31 de enero del año 2,000. Inscrita ante la  Superintendencia de Administración Tributaria (SAT) el 04 de febrero del año 2,000 con la actividad de transporte de pasajeros y carga por carretera.' | trans}}</p>
					</li>
					<li>
						<p class="font-medium">{{'Visión' | trans}}</p>
						<p>{{'Ser  una empresa de transporte de  pasajeros y encomienda, a la vanguardia en la aplicación de tecnología, garantizando un servicio de calidad y confort.' | trans}}</p>
					</li>
					<li>
						<p class="font-medium">{{'Misión' | trans}}</p>
						<p>{{'Ser líderes en el servicio de transporte de  pasajeros y encomienda nacional e internacional, ofreciendo un servicio de calidad a nuestros clientes, una fuente de trabajo estable para nuestros empleados, beneficio para el desarrollo social y económico del país; basado en la eficiencia y  actitudes orientadas a la satisfacción del cliente y a la mejora continua.' | trans}}</p>
					</li>
					<li>
						<p class="font-medium">{{'Objetivos' | trans}}</p>
						<ul>
							<li>
								<p>{{'Ofrecer el mejor servicio de transporte de pasaje y encomiendas, de manera segura y confiable.' | trans}}</p>
							</li>
							<li>
								<p>{{'Velar porque todo el personal aplique las normas y procedimientos de la empresa en la prestación de todos los servicios.' | trans}}</p>
							</li>
							<li>
								<p>{{'Garantizar la eficiencia y seguridad, para que se proporcione a los clientes, el mejor servicio posible.' | trans}}</p>
							</li>
						</ul>
					</li>
					<li>
						<p class="font-medium">{{'Estrategias' | trans}}</p>
						<ul>
							<li>
								<p>{{'Servicio al cliente. El cliente por encima de todo.' | trans}}</p>
							</li>
							<li>
								<p>{{'Introducir nuevas unidades de autobuses. satisfacer a los clientes con comodidad, seguridad y confort.' | trans}}</p>
							</li>
							<li>
								<p>{{'Ofrecer nuevos servicios. autobuses de lujo con a/c, tv y baño, servicio de encomiendas de puerta a puerta para satisfacción de nuestros clientes.' | trans}}</p>
							</li>
						</ul>
					</li>
					<li>
						<p class="font-medium">{{'Valores' | trans}}</p>
						<ul>
							<li>
								<p>{{'Honestidad. Sabemos que en la honestidad está basado el logro de los objetivos y la permanencia en el mercado, por ello, hacemos de este valor el eje fundamental de todas nuestras operaciones, tanto hacia los clientes, como hacia todas y cada una de las personas que aportan su talento y servicio a nuestra empresa; reconocemos nuestras fuerzas y nos esforzamos por superar nuestras debilidades día a día.' | trans}}</p>
							</li>
							<li>
								<p>{{'Respeto. Estamos convencidos de que a través del respeto por las personas y por todos los compromisos adquiridos, podremos lograr el posicionamiento de nuestra empresa y el reconocimiento de la calidad de los servicios que prestamos.' | trans}}</p>
							</li>
							<li>
								<p>{{'Trabajo. Creemos que el trabajo es la fuente primordial de beneficios para todos aquellos que se involucran en nuestras operaciones y que el único indicador de los esfuerzos que realizamos es el resultado.' | trans}}</p>
							</li>
							<li>
								<p>{{'Tecnología. Reconocemos la importancia de la tecnología en el logro de nuestras metas y estamos comprometidos en su aplicación y desarrollo para alcanzar la vanguardia de calidad en servicio y la puntualidad en los destinos  que nuestros clientes nos confían.' | trans}}</p>
							</li>
							<li>
								<p>{{'Seguridad. Sabemos la responsabilidad que conlleva nuestra operación, por eso dimensionamos la importancia de apegarnos a sistemas y procedimientos que salvaguarden la integridad de los clientes que transportamos y de las personas que intervienen en su traslado.' | trans}}</p>
							</li>
						</ul>
					</li>
				</ul>
			</div>
		</div>
	</section>
{% endblock %}

templates/macros.html.twig
{% macro reservacion_pdf_salida(reservacion, regreso = false) %}
	<div class="row">
		<div class="span2 text-right">{{'Fecha' | trans}}:</div>
		<div class="span5">
			<strong>{{ (regreso ? reservacion.regreso.salidaFecha : reservacion.salida.salidaFecha )| date(app.request.locale == 'es' ? 'd/m/Y' : 'Y-m-d') ~ ' ' ~ reservacion.salida.hora }}</strong>
		</div>
	</div>
	<div class="row">
		<div class="span2 text-right">{{'Asientos' | trans}}:</div>
		<div class="span5">
			<strong>
				{% for asiento in regreso ? reservacion.regreso.asientos : reservacion.salida.asientos %}
					{{ asiento.numero}}{{not loop.last ? ', '}}
				{% endfor %}
			</strong>
		</div>
	</div>
	<div class="row">
		<div class="span2 text-right">{{'Estación salida' | trans}}:</div>
		<div class="span8">{{regreso ? reservacion.ruta.estacionLlegada.nombre : reservacion.ruta.estacionSalida.nombre}}</div>
	</div>
	<div class="row">
		<div class="span2 text-right">{{'Dirección' | trans}}:</div>
		<div class="span8">{{regreso ? reservacion.ruta.estacionLlegada.direccion : reservacion.ruta.estacionSalida.direccion}}</div>
	</div>
	<div class="row">
		<div class="span2 text-right">{{'Estación llegada' | trans}}:</div>
		<div class="span8">{{regreso ? reservacion.ruta.estacionSalida.nombre : reservacion.ruta.estacionLlegada.nombre}}</div>
	</div>
	<div class="row">
		<div class="span2 text-right">{{'Dirección' | trans}}:</div>
		<div class="span8">{{regreso ? reservacion.ruta.estacionSalida.direccion : reservacion.ruta.estacionLlegada.direccion}}</div>
	</div>
{% endmacro %}

templates/servicio.html.twig
{% extends 'base.html.twig' %}

{% block body %}

	<section class="p-5 sm:p-20">
		<div class="container mx-auto">
			<div class="text-2xl text-center font-semibold">{{'Nuestros Servicios' | trans}}</div>
			<div class=" grid gap-8 grid-cols-1 divide-y">
				{% for key, servicio in servicios %}
					<div id="{{servicio.slug}}" class="pt-10 grid sm:block">
						<picture class="float-left mr-5 mb-5 shadow-lg max-w-[250px]">
							<source srcset="{{ servicio.imagen.path | imagine_filter('imagen_servicio') }}" type="image/webp">
							<source srcset="{{ servicio.imagen.path | imagine_filter('imagen_servicio') }}" type="image/jpeg">
							<img class="rounded-md" src="{{ servicio.imagen.path | imagine_filter('imagen_servicio') }}" alt="{{servicio.imagen.nombre}}">
						</picture>
						<div class="prose prose-base max-w-none">
							<h3 class="">{{servicio.nombre}}</h3>
							{{servicio.texto | raw}}
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
	</section>
{% endblock %}